### ISSUE TITLE
Not able to run new design

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD-flow-scripts#124]
Its basic question. I ran new designs by adding into container path ./designs/sky130hd/newdesign last week. After git pull latest update, if I run new design by copying file to docker container its fail with  error; 
If I create source file manually its working fine. Only if I copied files from local to container, its throwing below error
**bash-4.2$ make DESIGN_CONFIG=./designs/nangate45/eth_top/config.mk
[INFO][FLOW] Using platform directory ./platforms/nangate45
make: * platforms/nangate45: Is a directory. Stop.**

In-build design aes/riscv32i etc able to run successfully. using #make command

**Comment by vvbandeira** [comment]
@vijayank88 could you provide as many as possible of the following:

- Test case (design source if public and `config.mk`) either a tarball or link to GitHub repository
- Git hash you are using
- Step-by-step to reproduce the error
- Complete log/commands output

Also, you first mentions `sky130hd` and the error mentions `nangate45`, possibly the issue is with your `config.mk`

**Comment by vijayank88** [comment]
@vvbandeira  my problem is completely different.
OpenRoad inbuilt example working fine. Even if I create new project and src file within docker container able to proceed without any issue.
Only if I copy source file directory (RTL Codes) from local system to Docker I'm facing above error message.

**Comment by vijayank88** [comment]
Just found it default shell is csh.. I switched to bash mode and used docker cp and there is no such error. Thanks
