### ISSUE TITLE
Please add a setHard method to set the blockage to HARD

### ISSUE THREAD

**Issue by huang-kaixin** [The-OpenROAD-Project/OpenROAD-flow-scripts#1466]
### Description

I want to set the blockage around the macro to hard, preventing standard cells from being placed in this area. However, I found that the blockage only has the setSoft method. This results in standard cells crowding between the two macros after the detail_place step, causing global routing congestion to become too high and terminate. I tried deleting the $b setSoft command in placement_blockages.tcl, setting soft to false, but standard cells can still be placed in the blockage. Is my approach incorrect? Could you please consider adding a setHard method to set the blockage around the macro to hard and prevent standard cells from being placed in this area?Thank you in advance for your response!
![微信图片_20230914173806](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/111551571/0a16ea8e-f3ba-4196-af0a-4e0ccad8a855)

**Comment by maliberty** [comment]
Blockages are hard by default so there is no need for such a method.  We don't allow global placement to put cells inside a hard blockage but we do allow timing optimization to do so as otherwise it is often impossible to fix problems.    From your image I would guess you have a timing issue there (perhaps hold?).
