### ISSUE TITLE
/bin/sh: 0: Illegal option -o pipefail : While running example design

### ISSUE THREAD

**Issue by mistryalok** [The-OpenROAD-Project/OpenROAD-flow-scripts#440]
I am hitting below error while running example design,

[INFO][FLOW] Using platform directory ./platforms/nangate45
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
make: *** [Makefile:311: objects/nangate45/swerv/base/lib/NangateOpenCellLibrary_typical.lib] Error 2
(reverse-i-search)`DE': make ^CSIGN_CONFIG=./designs/nangate45/swerv/config.mk

However, later I tweaked OpenROAD-flow-scripts/flow/Makefile with below change & It seems to be worked fine after that.

-.SHELLFLAGS    = -o pipefail -c
+SHELLOPTS = -o pipefail -c

**Comment by vvbandeira** [comment]
Some other users had similar problems. We were not able to track down the root cause, but we suspect is due to some local configuration in the user's environment. You can read the discussion here: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/discussions/330. I will mark it as closed since the discussion ended with an Answer, please feel free to comment further on the discussion or re-open the issue if there is new information.
