### ISSUE TITLE
OpenROAD-flow-scripts does not update OpenROAD to latest version

### ISSUE THREAD

**Issue by lulu9312** [The-OpenROAD-Project/OpenROAD-flow-scripts#562]
Describe the bug
I recently updated ORFS but the OpenROAD under tools folder does not seem to be updated 

Expected behavior
OpenROAD under tools folder should be updated to latest version

Screenshots
Attaching a file that's updated in OpenROAD but not in ORFS
![or_update](https://user-images.githubusercontent.com/61928883/185385747-b97a5490-1326-4c1c-a85e-724e8461ae4b.png)

**Comment by vvbandeira** [comment]
OpenROAD-flow-scripts always point to a version of OpenROAD that is "known as good/stable" for the designs in ORFS, so is expected that most of the time it stays behind OpenROAD/master. In other words, updating ORFS to the latest master does not guarantee that (and is not expected to) have the latest OpenROAD.

You can use `--latest` flag with `./build_openroad.sh` to force ORFS to use OpenROAD/master.

If you have any more questions or need help feel free to keep replying to this thread, but I will mark it as close since this is the expected behaviour.
