### ISSUE TITLE
Add recursive ssh cloning support

### ISSUE THREAD

**Issue by abettati** [The-OpenROAD-Project/OpenROAD-flow-scripts#865]
### Description

At the moment the suggested method for cloning is https.
This can lead (as it happened to me) to problems dealing with certificates, errors like:
```
fatal: unable to access 'https://github.com/The-OpenROAD-Project/OpenROAD.git/': server certificate verification failed. CAfile: none CRLfile: none
```
This is true even trying to clone with ssh, as submodule are still cloned with https.

### Suggested Solution

We could add support for ssh in submodules as well.

**Comment by vvbandeira** [comment]
There's nothing to change on our side. Both methods, https and ssh, are supported by git and GitHub and are transparent to all projects/repositories. The missing certificates are likely missing or out-of-date on your system.

Try to run the command below if you are on Ubuntu or Debian OS. Otherwise, replace the command with the equivalent for the pacakge manager of your OS.
```
sudo apt install -y ca-certificates
```

**Comment by vijayank88** [comment]
@abettati 
Hope this is resolved and closing this issue. Feel free to re-open if further helps required.
